apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajay-deploy
  labels:
    app: ajay-mvn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajay-mvn-app
  template:
    metadata:
      labels:
        app: ajay-mvn-app
    spec:
      containers:
      - name: ajay-mvn-container
        image: ajay206/mvn_apps:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ajay-np-service
  labels:
    app: ajay-mvn-app
spec:
  selector:
    app: ajay-mvn-app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
